### ISSUE TITLE
Poblar base de datos con datos iniciales

### ISSUE THREAD

**Issue by rafaelferrero** [bvsf/backdraft#67]
Se necesita crear datos iniciales en la base de datos. Estos se deben poblar con el migrate.

Especificamente:
En los Grados, Rangos y Escalafon
En las Localidades (las de los bomberos actuales*), Provincias (todas las argentinas) y Países (con argentina basta).
En los Alérgenos (los más comunes)
*Le podes pedir a @cristiancarle que te emita un listado de las localidades desde el sistema actual

**Comment by lokiyin** [comment]
porfavor algunos bomberos personas madres padres y hijos.

**Comment by rafaelferrero** [comment]
Claro, aprovechamos el conocimiento para luego migrar los datos del sistema viejo al nuevo.

**Comment by fmoreyra** [comment]
Rafa, es más o menos a esto lo que te referís? https://docs.djangoproject.com/en/1.9/howto/initial-data/ Si es así crear los json sería sencillo...

**Comment by fmoreyra** [comment]
perdón, le pifié de botón

**Comment by rafaelferrero** [comment]
TIENE TODA LA PINTA DE SER EXACTAMENTE LO QUE NECESITAMOS !!
Habría que crear unos JSON con los datos de Países, Provincias y
Localidades.
Luego podemos usar la misma técnica, tal vez, para migrar los datos de los
bomberos del sistema viejo al nuevo.


Rafael E. Ferrero

2017-05-20 0:02 GMT-03:00 fmoreyra <notifications@github.com>:

**Comment by fmoreyra** [comment]
Probé hacerlo en mi entorno y efectivamente funciona, me haría falta el listado de @cristiancarle para poder agregar las localidades solicitadas.
